# Generated by Django 3.2.6 on 2021-08-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('spend_other', models.IntegerField()),
                ('spend_alchohol', models.IntegerField()),
                ('spend_meat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('sober', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('goup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.party'),
        ),
    ]
